- uses: lowlighter/metrics@latest
  with:
    token: ${{ secrets.METRICS_TOKEN }}
    plugin_achievements: yes
    plugin_achievements_display: compact
    plugin_isocalendar: yes
    plugin_isocalendar_duration: half-year
